# Generated by Django 4.2.23 on 2025-07-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_COMPLETED', 'Task Completed'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('MESSAGE_SENT', 'Message Sent'), ('RECORD_UPLOADED', 'Record Uploaded'), ('REPORT_FILTERED', 'Report Filtered')], max_length=20),
        ),
    ]
