# Generated by Django 4.2.23 on 2025-07-07 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('dark_mode', models.BooleanField(default=False)),
                ('email_tasks', models.BooleanField(default=True)),
                ('email_reports', models.BooleanField(default=True)),
                ('email_security', models.BooleanField(default=True)),
                ('push_tasks', models.BooleanField(default=True)),
                ('push_meetings', models.BooleanField(default=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
