# Generated by Django 4.2.23 on 2025-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Document', 'Document'), ('Video', 'Video'), ('Audio', 'Audio'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.DeleteModel(
            name='RecordType',
        ),
    ]
